| <p>Ingeniería en Control de Gestión</p> <p>Métodos Cuantitativos</p> <p>Unidad I: Estadística y Probabilidades con Python</p> <p>Semana 2: Manejo básico de Python</p>|
|:--- |

# 1 Introducción a los Tipos de Datos en Python

En esta sesión, exploraremos los tipos de datos fundamentales en Python, esenciales para manipular información y realizar operaciones en el lenguaje.


Comprender los tipos de datos es fundamental para escribir código eficiente y evitar errores en el procesamiento de la información.

En la sesión anterior, nos enfocamos en tres categorías principales:

1. **Tipos Numéricos (`int`, `float`, `complex`)**: Representan valores numéricos y permiten operaciones matemáticas.
2. **Tipo de Texto (`str`)**: Manejo de cadenas de caracteres y técnicas avanzadas como formateo y caracteres de escape.
3. **Tipos Booleanos (`bool`)**: Representación de valores lógicos (`True` y `False`), operadores lógicos y comparaciones.


## 1.1 El valor `None` en Python
`None` es un objeto especial en Python que representa la ausencia de un valor o un valor nulo. Se utiliza para indicar que una variable no tiene un valor asignado.

In [1]:
variable = None
print(variable)

None


Para verificar si una variable es `None`, se usa is en lugar de `==`:

In [2]:
if variable is None:
    print("La variable no tiene un valor asignado")

La variable no tiene un valor asignado


# 2 Introducción a las Estructuras de Datos en Python

Las **estructuras de datos** son formas organizadas de almacenar, gestionar y manipular información en un programa. En Python, existen varias estructuras que permiten trabajar con diferentes tipos de datos de manera eficiente.


## 2.1 ¿Por qué son importantes las estructuras de datos?
Las estructuras de datos son fundamentales en programación porque:
- Permiten organizar y acceder a la información de manera eficiente.
- Optimizan el uso de memoria y procesamiento.
- Son clave en la resolución de problemas computacionales y algoritmos.


## 2.2 Tipos de Estructuras de Datos en Python
Python proporciona varias estructuras de datos incorporadas (*built-in*), cada una con características y usos específicos:


### Listas (`list`)
Las listas son estructuras **ordenadas** y **mutables**, lo que significa que podemos modificar sus elementos después de su creación.


In [6]:
mi_lista = [10, 20, 30, "Python", 'Hola']
mi_lista.append(40)
print(mi_lista)

[10, 20, 30, 'Python', 'Hola', 40]


In [7]:
print(mi_lista[-1])

40


In [9]:
mi_lista[-1] = 60

In [10]:
print(mi_lista)

[10, 20, 30, 'Python', 'Hola', 60]


### Tuplas (`tuple`)

Las tuplas son similares a las listas, pero inmutables (no pueden modificarse después de su creación).

In [14]:
mi_tupla = (1, 2, 3, "Python")
print(mi_tupla[0])
print(mi_tupla[1])
print(mi_tupla[2])

1
2
3


In [15]:
print(mi_tupla[-1])
print(mi_tupla[-2])

Python
3


In [16]:
# Error: las tuplas son inmutables
mi_tupla[-1] = 40

TypeError: 'tuple' object does not support item assignment

### Diccionarios (`dict`)

Los diccionarios almacenan datos en pares clave-valor, permitiendo acceso rápido a los valores a través de sus claves.

In [19]:
mi_diccionario = {
    "nombre": "Juan",
    "edad": 25,
    "ciudad": "Santiago"
}

print(mi_diccionario["nombre"])

Juan


### Conjuntos (`set`)

Los conjuntos son estructuras desordenadas que almacenan elementos únicos.

In [20]:
mi_conjunto = {1, 2, 3, 3, 4}
print(mi_conjunto)

{1, 2, 3, 4}


## 2.3 NumPy

**NumPy** (*Numerical Python*) es una biblioteca que proporciona soporte para **arrays multidimensionales** y funciones matemáticas de alto rendimiento. Es utilizada principalmente para realizar operaciones numéricas eficientes, ya que está optimizada para cálculos vectorizados.


### Características principales de NumPy
- Soporte para **arrays multidimensionales (`ndarray`)**  
- Operaciones matemáticas y algebraicas optimizadas  
- Integración con otras bibliotecas científicas como `SciPy`, `Matplotlib` y `Pandas`  
- Mayor eficiencia en memoria y velocidad en comparación con listas de Python  

### Vectores en NumPy

Un vector es un array unidimensional, usado comúnmente en álgebra lineal y machine learning.

In [21]:
# importamos la librería de NumPy con el alias 'np'
import numpy as np

vector = np.array([5, 10, 15])
print(vector)

[ 5 10 15]


#### Operaciones comunes con vectores

In [22]:
# multiplicar por un escalar
print(vector * 2)

[10 20 30]


In [23]:
# obtener la media del vector
print(np.mean(vector))

10.0


In [24]:
# obtener la suma acumulada del vector
print(np.cumsum(vector))

[ 5 15 30]


In [25]:
# obtener la suma total del vector
print(np.sum(vector))

np.int64(30)

In [30]:
# operaciones entre vectores
vector_1 = np.array([3, 4, 5])
vector_2 = np.array([7, 8, 9])

In [31]:
# suma
print(vector_1 + vector_2)

[10 12 14]


In [32]:
# resta
print(vector_1 - vector_2)

[-4 -4 -4]


In [33]:
# multiplicación
print(vector_1 * vector_2)

[21 32 45]


In [34]:
# división
print(vector_1 / vector_2)

[0.42857143 0.5        0.55555556]


### Matrices en NumPy

Una matriz es un array bidimensional, representado como una tabla con filas y columnas.

In [35]:
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(matriz)

[[1 2 3]
 [4 5 6]]


In [36]:
# obtener la dimensión (fila, columna)
print(matriz.shape)

(2, 3)


#### Operaciones comunes con matrices

In [ ]:
# transponer la matriz
print(matriz.T)

In [ ]:
# producto punto
print(np.dot(matriz, matriz.T))

### Diferencias entre listas y arrays de NumPy

| **Característica**       | **Lista de Python**    | **Array de NumPy** |
|-------------------------|----------------------|--------------------|
| **Tipo de datos**      | Permite distintos tipos | Requiere tipos homogéneos |
| **Eficiencia en memoria** | Menos eficiente         | Más eficiente |
| **Soporte para cálculos** | Operaciones manuales    | Operaciones vectorizadas rápidas |

## 2.4 Pandas

**Pandas** es una biblioteca diseñada para manejar y analizar datos estructurados en **Series** y **DataFrames**. Se basa en NumPy y permite trabajar con grandes volúmenes de datos de manera eficiente.

### Series en Pandas

Una **Serie** en Pandas es una estructura de **una sola columna** con un índice asociado. Es similar a un **array de NumPy**, pero con etiquetas para cada valor.

In [37]:
# importamos la librería Pandas con el alias 'pd'
import pandas as pd

# crear una Serie en Pandas
serie = pd.Series(
    data=[10, 20, 30], # valores
    index=["2000", "2001", "2002"] # indices
)
print(serie)

2000    10
2001    20
2002    30
dtype: int64


#### Operaciones comunes en Series

In [38]:
# acceder a un valor a través del índice
print(serie["2000"])

10


In [39]:
# calcular el promedio
print(serie.mean())

20.0


In [40]:
# calcular la suma acumulada
print(serie.cumsum())

2000    10
2001    30
2002    60
dtype: int64


In [41]:
# calcular la suma de la serie
print(serie.sum())

60


## DataFrames en Pandas

Un **DataFrame** es una estructura tabular de **múltiples columnas**, similar a una hoja de cálculo o tabla de base de datos.

In [43]:
datos = {
    "Nombre": ["Ana", "Carlos", "Sofía"],
    "Edad": [25, 30, 22]
}
df = pd.DataFrame(datos)
df

,Nombre,Edad
0,Ana,25
1,Carlos,30
2,Sofía,22


#### Operaciones comunes en DataFrames

In [46]:
# primeras filas (por defecto 5)
print(df.head())

   Nombre  Edad
0     Ana    25
1  Carlos    30
2   Sofía    22


In [47]:
# primeras n filas
print(df.head(1))

  Nombre  Edad
0    Ana    25


In [48]:
# ultimas n filas
print(df.tail(1))

  Nombre  Edad
2  Sofía    22


In [49]:
# estadísticas de columnas numéricas
print(df.describe())

            Edad
count   3.000000
mean   25.666667
std     4.041452
min    22.000000
25%    23.500000
50%    25.000000
75%    27.500000
max    30.000000


In [51]:
# promedio de la columna "Edad"
print(df["Edad"].mean())

25.666666666666668


### ¿Cuándo usar NumPy y Pandas?
-	🏎 **NumPy** es ideal para **cálculos numéricos** y **procesamiento de datos en matrices**.
-	📊 **Pandas** es mejor cuando trabajas con **tablas de datos (como hojas de cálculo o bases de datos)**.


**Ejemplo combinado**: Usar NumPy y Pandas juntos en análisis de datos.

In [ ]:
# aplicar una función matemática a una columna
df["log_edad"] = np.log(df["Edad"])
print(df)

# 3 Estructuras de Control de Flujo

- Python permite controlar la ejecución de un programa a través de **estructuras de control de flujo**, como condicionales (`if`, `else`) y bucles (`for`, `while`).
- Las estructuras de control permiten modificar el flujo de ejecución de un programa con **condicionales** y **bucles**.



## 3.1 Condicionales (`if`, `elif`, `else`)
Las condicionales permiten ejecutar código dependiendo de una condición.

In [55]:
edad = 18

if edad >= 18:
  print("Eres mayor de edad")
else:
  print("Eres menor de edad")

Eres mayor de edad


### Uso de `elif` (else if)

Podemos agregar más condiciones con elif:

In [62]:
nota = 55

if nota >= 65:
    print("Excelente")
elif nota >= 50:
    print("Muy bien")
elif nota >= 40:
    print("Aprobado")
else:
    print("Reprobado")

Muy bien


📌 Nota: Python usa **indentación** para definir bloques de código.

In [70]:
edad = 50

if edad <=2:
    print("Bebe")
elif edad <= 14:
    print("Niño")
elif edad <= 20:
    print("Adolecente")
elif edad <= 40:
    print("Adulto Joven")
elif edad <= 60:
    print("Adulto")
else:
    print("Adulto Mayor")

Adulto


![elif2.png](https://drive.google.com/uc?id=12okuqj3ykoERMzgAyw7fVgnRsjDHYB9o)

## 3.2 Bucles en Python

Los bucles permiten repetir instrucciones múltiples veces.

### Bucle `for`

Se usa para iterar sobre secuencias como listas, tuplas o rangos.

In [71]:
frutas = ["Manzana", "Banana", "Cereza"]

# por cada elemento dentro de la lista frutas
for fruta in frutas:
    print(fruta)

Manzana
Banana
Cereza


In [72]:
# el iterador puede tener el nombre que determine más conveniente
for elemento in frutas:
    print(elemento)

Manzana
Banana
Cereza


#### Uso de `range()` en `for`

In [73]:
# iterara de 0 a 4 (el método range no incluye el punto de corte)
for i in range(5):
    print(i)

0
1
2
3
4


In [77]:
# empezar en 1 e iterar hasta 4
for i in range(1, 5):
    print(i)

1
2
3
4


In [78]:
# empezar en 2 e iterar hasta 10, de 2 en 2
for i in range(2, 11, 2):
    print(i)

2
4
6
8
10


### Bucle `while`

Ejecuta el bloque de código mientras la condición sea True.

In [81]:
contador = 0

while contador < 3:
    print(f"Iteración {contador}")
    contador += 1

Iteración 0
Iteración 1
Iteración 2


#### `break` y `continue` en bucles
-	`break`: Detiene el bucle.
-	`continue`: Salta a la siguiente iteración.

In [82]:
for i in range(5):
    if i == 3:
        break  # detiene el bucle cuando i es 3
    print(i)

0
1
2


In [85]:
for i in range(5):
    if i == 2:
        continue  # salta el valor 2 y sigue con la siguiente iteración
    print(i)

0
1
3
4


# 4 Creación de Funciones en Python

- Las funciones en Python permiten modularizar el código, haciéndolo más **organizado, reutilizable y eficiente**.
- En esta sección, exploraremos en profundidad cómo definir funciones, utilizar parámetros, valores de retorno y otros conceptos avanzados.


## 4.1 ¿Qué es una función?
Una **función** es un bloque de código reutilizable que se ejecuta solo cuando se llama. Se pueden pasar datos a la función como **parámetros** y devolver valores usando `return`.


## 4.2 Definir una Función con `def`

Las funciones en Python se definen con la palabra clave `def`, seguida del **nombre de la función** y paréntesis `()`, donde pueden ir los **parámetros**.


In [91]:
def saludar():
    print("¡Hola, bienvenido a Python!")

In [93]:
# llamar la función
print(saludar())

¡Hola, bienvenido a Python!
None


## 4.3 Parámetros en Funciones

Los **parámetros** permiten que una función reciba valores para procesarlos dentro de su bloque de código.

In [95]:
# @title Función con Parámetros
def saludar(nombre):
    print(f"Hola, {nombre}")

alumno = "Victor"
saludar(alumno)
saludar("Carlos")
saludar("Ana")

Hola, Victor
Hola, Carlos
Hola, Ana


Las funciones también nos permite usar valores por defecto, en caso que no se proporcione un valor.

In [96]:
# @title Parámetros con valores predeterminados

def saludar(nombre="Invitado"):
    print(f"Hola, {nombre}")

saludar("Elena")
saludar()

Hola, Elena
Hola, Invitado


In [97]:
# @title Función con múltiples Parámetros

def sumar(a, b):
    return a + b  # Devuelve la suma de a y b

resultado = sumar(4, 7)
print(resultado)

11


## 4.4 Retorno de Valores con `return`

Una función puede devolver un resultado con la palabra clave return.

In [98]:
def cuadrado(numero):
    return numero ** 2

resultado = cuadrado(5)
print(resultado)

25


Si una función no tiene `return`, devuelve `None` por defecto:

In [99]:
def sin_retorno():
    print("Esta función no devuelve nada")

print(sin_retorno())

Esta función no devuelve nada
None


## 4.5 Argumentos Variables en Funciones

### 4.5.1 `*args`: Múltiples argumentos posicionales

Cuando no sabemos cuántos argumentos se pasarán a una función, podemos usar `*args` para recibir varios valores.

In [101]:
def sumar_todos(*numeros):
    return sum(numeros)

print(sumar_todos(1, 2, 3, 4, 5, 6))

21


📌 ***args recibe los valores como una tupla**.


### 4.5.2 `**kwargs`: Múltiples argumentos con claves

`**kwargs` permite pasar múltiples argumentos con nombres clave-valor.

In [102]:
def mostrar_info(**datos):
    for clave, valor in datos.items():
        print(f"{clave}: {valor}")

mostrar_info(nombre="Ana", edad=25, ciudad="Santiago")

nombre: Ana
edad: 25
ciudad: Santiago


📌 ****kwargs recibe los valores como un diccionario**.

## 4.6 Funciones Anidadas

Las funciones pueden definirse dentro de otras funciones.

In [103]:
def externa():
    print("Esta es la función externa.")

    def interna():
        print("Esta es la función interna.")

    interna()

externa()

Esta es la función externa.
Esta es la función interna.


## 4.7 Funciones Lambda (Funciones Anónimas)

Las **funciones lambda** son expresiones cortas sin nombre que permiten definir funciones en una sola línea.

In [104]:
doblar = lambda x: x * 2
print(doblar(5))

10


Otro ejemplo con dos parámetros:

In [ ]:
multiplicar = lambda a, b: a * b
print(multiplicar(3, 4))

📌 **Se usan comúnmente en funciones como `map()`, `filter()`, y `sorted()`**.

## 4.8 Alcance de Variables en Funciones

El **ámbito** de una variable determina dónde puede ser utilizada.


### 4.8.1 Variables Locales y Globales
-	**Variable local**: Definida dentro de una función y solo accesible dentro de ella.
-	**Variable global**: Definida fuera de cualquier función y accesible desde cualquier parte del programa.

In [ ]:
nombre_global = "Python"

def funcion():
    nombre_local = "Curso"
    print(nombre_global)  # se puede acceder a la variable global
    print(nombre_local)  # solo accesible dentro de la función

funcion()

In [ ]:
# Error: la variable no está definida fuera de la función
print(nombre_local)

📌 **Evita modificar variables globales dentro de funciones, ya que puede causar errores difíciles de depurar**.

## 4.9 Funciones Recursivas

Una **función recursiva** es aquella que se llama a sí misma para resolver problemas repetitivos.

In [105]:
def factorial(n):
    if n == 1:
        return 1
    return n * factorial(n - 1)

print(factorial(5))

120
