|<img src="https://drive.google.com/uc?id=1kjzJXxk2dJDr_oNKOqgGjBPbu4v-s0NW" width="100px" height="100">| <p> Métodos Cuantitativos</p> <p>Ingeniería en Control de Gestión</p> <p>Unidad I: Estadística y Probabilidades con Python</p> <p>Sesión 6: Distribuciones continuas</p>|
|:--- |:---|

# Semilla en Python

Una semilla (seed) se usa en contextos como generación de números pseudoaleatorios para inicializar el generador de números aleatorios en un valor particular. Esto asegura que los resultados sean reproducibles si se utiliza la misma semilla.

In [ ]:
# @title Valores pseudoaleatorios
from scipy.stats import binom

# creamos 10 muestras de una variable aleatoria X ~ binom(0.5, 10)

binom.rvs(p=0.5, n=10, size=10)

array([4, 6, 5, 7, 5, 5, 5, 3, 4, 6])

In [ ]:
# @title Semilla con scipy
from scipy.stats import binom

# creamos 10 muestras de una variable aleatoria X ~ binom(0.5, 10)
# el argumento `random_state` fija la semilla,
# en este caso con en el valor `2024`

binom.rvs(p=0.5, n=10, size=10, random_state=2024)

array([5, 6, 4, 2, 4, 3, 6, 6, 5, 5])

In [ ]:
# @title Semilla con NumPy
from scipy.stats import binom
import numpy as np

# creamos 10 muestras de una variable aleatoria X ~ binom(0.5, 10)
# la función `np.random.seed` fija la semilla,
# en este caso con en el valor `2024`

np.random.seed(2024)
binom.rvs(p=0.5, n=10, size=10)

array([5, 6, 4, 2, 4, 3, 6, 6, 5, 5])

# scipy.stats

El módulo `stats` de la librería `SciPy` contiene una gran cantidad de distribuciones de probabilidad, estadísticas de resumen y frecuencia, funciones de correlación y pruebas estadísticas, estimación de densidad de kernel, funcionalidad de cuasi-Monte Carlo y más.

Documentación de la librería: [https://docs.scipy.org/doc/scipy/reference/stats.html](https://docs.scipy.org/doc/scipy/reference/stats.html)


# Distribución Uniforme Discreta

La distribución uniforme discreta modela experimentos donde cada resultado tiene la misma probabilidad de ocurrir dentro de un rango finito de valores. En esta distribución, la probabilidad de cada valor dentro del rango es constante y se distribuye uniformemente.

**Notación:**
- $X \sim \text{Uniforme}(a, b)$

**Donde:**
- $a$: Valor mínimo en el rango de la distribución.
- $b$: Valor máximo en el rango de la distribución.

**Ejemplo:**

Imaginemos que lanzamos un dado justo de seis caras. La distribución uniforme discreta se puede utilizar para modelar las probabilidades de obtener cada número en el dado. Cada número del 1 al 6 tiene la misma probabilidad de ocurrir, es decir, $\frac{1}{6}$. Podemos usar esta distribución para calcular la probabilidad de obtener un número específico, como calcular la probabilidad de obtener un 3.

In [ ]:
# @title Variable aleatoria
from scipy.stats import randint

# ejemplo: X ~ Uniforme(1, 10)
valor_minimo = 1
valor_maximo = 10

# crear variable aleatoria
va = randint.rvs(low=valor_minimo, high=valor_maximo + 1)  # sumamos 1 al valor máximo para incluirlo
print(va)

8


In [ ]:
# @title Variable aleatoria: múltiples muestras
from scipy.stats import randint

# ejemplo: X ~ Uniforme(1, 10)
valor_minimo = 1
valor_maximo = 10
muestras_aleatorias = 5

# crear variable aleatoria
va = randint.rvs(low=valor_minimo, high=valor_maximo + 1, size=muestras_aleatorias)
print(va)

[ 8  7  3  8 10]


## Función de Masa de Probabilidad (PMF)

$$ P(X = k) = \frac{1}{{b - a + 1}} $$

Donde:
- $ P(X = k) $ es la probabilidad de que la variable aleatoria $ X $ tome el valor $ k $.
- $ a $ es el valor mínimo en el rango de la distribución.
- $ b $ es el valor máximo en el rango de la distribución.
- $ b - a + 1 $ es el tamaño del rango de la distribución, que representa el número total de valores posibles que puede tomar la variable aleatoria.


In [ ]:
from scipy.stats import randint

# ejemplo: X ~ Uniforme(1, 10)
valor_minimo = 1
valor_maximo = 10
k = 4

# probabilidad de obtener exactamente el valor 3
randint.pmf(k=k, low=valor_minimo, high=valor_maximo + 1)

0.1

## Función de Distribución Acumulativa (CDF)

$$ F(k; a, b) = \frac{{\lfloor k \rfloor - a + 1}}{{b - a + 1}} $$

Donde:
- $ F(k; a, b) $ es la probabilidad de que la variable aleatoria $ X $ tome un valor menor o igual que $ k $.
- $ a $ es el valor mínimo en el rango de la distribución.
- $ b $ es el valor máximo en el rango de la distribución.
- $ \lfloor k \rfloor $ es la parte entera de $ k $.


In [ ]:
from scipy.stats import randint

# ejemplo: X ~ Uniforme(1, 10)
valor_minimo = 1
valor_maximo = 10
k = 3

# probabilidad de obtener un valor igual o menor a 3
randint.cdf(k=k, low=valor_minimo, high=valor_maximo + 1)

0.3

## Esperanza ($E$)

La esperanza de una distribución uniforme discreta es el valor medio de la distribución, es decir, el promedio ponderado de todos los posibles valores que puede tomar la variable aleatoria.

$$ E(X) = \frac{{a + b}}{2} $$

Donde:
- $ E(X) $ es la esperanza de la distribución uniforme discreta.
- $ a $ es el valor mínimo en el rango de la distribución.
- $ b $ es el valor máximo en el rango de la distribución.

In [ ]:
from scipy.stats import randint

# ejemplo: X ~ Uniforme(1, 6)
valor_minimo = 1
valor_maximo = 6

# crear distribución
distribucion = randint(low=valor_minimo, high=valor_maximo + 1)
distribucion.mean()

3.5

# Distribución Binomial

La distribución binomial modela el número de éxitos en una secuencia de ensayos independientes, donde cada ensayo tiene una probabilidad de éxito constante, $p$. Los ensayos son independientes entre sí y solo hay dos resultados posibles en cada ensayo: éxito o fracaso.

**Notación:**
- $X \sim Binomial(p, n)$

**Donde:**
- $p$: Probabilidad de éxito en un ensayo.
- $n$: Número de ensayos.

**Ejemplo:**

Imaginemos que lanzamos una moneda justa 10 veces y queremos saber la probabilidad de obtener exactamente 5 caras. Podemos modelar este escenario utilizando la distribución binomial, donde cada lanzamiento de la moneda es un ensayo independiente con una probabilidad de éxito $p = 0.5$ (probabilidad de obtener cara). El número total de ensayos es $n = 10$. Luego podemos utilizar la distribución binomial para calcular la probabilidad de obtener exactamente 5 caras en estos 10 lanzamientos.

In [ ]:
# @title Variable aleatoria
from scipy.stats import binom

# ejemplo: X ~ binom(0.5, 10)
probabilidad_exito = 0.5
n_ensayos = 10

# crear VA
va = binom.rvs(p=probabilidad_exito, n=n_ensayos)
print(va)

4


In [ ]:
# @title Variable aleatoria: múltiples muestras
from scipy.stats import binom

# ejemplo: X ~ binom(0.5, 10)
probabilidad_exito = 0.5
n_ensayos = 10
muestras_aleatorias = 5

# crear VA
va = binom.rvs(p=probabilidad_exito, n=n_ensayos, size=muestras_aleatorias)
print(va)

[6 6 4 3 8]


## Función de Masa de Probabilidad (PMF)

$$P(X = k) = \binom{n}{k} \cdot p^k \cdot (1 - p)^{n - k}$$

Donde:
- $P(X = k) $ es la probabilidad de que la variable aleatoria $X$ tome el valor $k$.
- $n$ es el número total de ensayos.
- $p$ es la probabilidad de éxito en un solo ensayo.
- $\binom{n}{k}$ es el coeficiente binomial, que representa el número de combinaciones de $k$ éxitos en $n$ ensayos.

In [ ]:
from scipy.stats import binom

# ejemplo: X ~ binom(0.5, 10)
probabilidad_exito = 0.5
n_ensayos = 10
exitos = 2

# probabilidad de obtener exactamente 2 caras de 10 lanzamientos de monedas justas
binom.pmf(k=exitos, n=n_ensayos, p=probabilidad_exito)

0.04394531250000004

In [ ]:
# ejemplo: X ~ binom(0.7, 10)
probabilidad_exito = 0.7
n_ensayos = 10
exitos = 5

# probabilidad de obtener exactamente 5 caras de 10 lanzamientos de monedas trucada
binom.pmf(k=exitos, n=n_ensayos, p=probabilidad_exito)

0.10291934519999998

## Función de Distribución Acumulativa (CDF)

$$F(k;n,p) = \sum_{i=0}^{k} \binom{n}{i} \cdot p^i \cdot (1-p)^{n-i}$$

Donde:
- $F(k;n,p)$ es la función de distribución acumulativa (CDF) para obtener $k$ o menos éxitos en $n$ ensayos, con una probabilidad e éxito $p$ en cada ensayo.
- $\binom{n}{i}$ es el coeficiente binomial, que representa el número de formas de elegir $i$ éxitos entre $n$ ensayos.
- $p$ es la probabilidad de éxito en un ensayo.
- $(1 - p)$ es la probabilidad de fracaso en un ensayo.
- $n$ es el número total de ensayos.

In [ ]:
from scipy.stats import binom

# ejemplo: X ~ binom(0.5, 10)
probabilidad_exito = 0.5
n_ensayos = 10
exitos = 5

# probabilidad de obtener 5 caras o menos de 10 lanzamientos de monedas justas
binom.cdf(k=exitos, n=n_ensayos, p=probabilidad_exito)

0.623046875

In [ ]:
# ejemplo: X ~ binom(0.7, 10)
probabilidad_exito = 0.7
n_ensayos = 10
exitos = 7

# probabilidad de obtener 7 caras o menos de 10 lanzamientos de monedas trucada
binom.cdf(k=exitos, n=n_ensayos, p=probabilidad_exito)

0.6172172136000001

## Función de Supervivencia (SF)

La función de supervivencia (también conocida como función de supervivencia acumulada) representa la probabilidad de que la variable aleatoria $X$ sea mayor que un valor específico $k$.

Para la distribución binomial, esta función se define como:

$$P(X > k) = \sum_{i=k+1}^{n} \binom{n}{i} \cdot p^i \cdot (1 - p)^{n - i}$$

Donde:
- $P(X > k)$ es la probabilidad de que la variable aleatoria $X$ sea mayor que $k$.
- $n$ es el número total de ensayos.
- $p$ es la probabilidad de éxito en un solo ensayo.
- $\binom{n}{i} $ es el coeficiente binomial, que representa el número de combinaciones de $i$ éxitos en $n$ ensayos.
- La suma se realiza desde $i = k+1$ hasta $i = n$.

In [ ]:
# ejemplo: X ~ binom(0.5, 10)
probabilidad_exito = 0.5
n_ensayos = 10
exitos = 6

# probabilidad de obtener más de 6 caras de 10 lanzamientos de monedas justas
binom.sf(k=exitos, n=n_ensayos, p=probabilidad_exito)

0.171875

In [ ]:
# ejemplo: X ~ binom(0.7, 10)
probabilidad_exito = 0.7
n_ensayos = 10
exitos = 7

# probabilidad de obtener más de 7 caras de 10 lanzamientos de monedas trucada
binom.sf(k=exitos, n=n_ensayos, p=probabilidad_exito)

0.38278278639999985

## Esperanza ($E$)

La esperanza de una distribución binomial es el número promedio de éxitos en una secuencia de ensayos independientes, donde cada ensayo tiene una probabilidad de éxito constante, $p$.

$$ E(X) = n \cdot p $$

Donde:
- $ E(X) $ es la esperanza de la distribución binomial.
- $ n $ es el número total de ensayos.
- $ p $ es la probabilidad de éxito en un solo ensayo.



In [ ]:
from scipy.stats import binom

# ejemplo: X ~ binom(0.5, 10)
probabilidad_exito = 0.5
n_ensayos = 10

# crear distribución
distribucion = binom(n=n_ensayos, p=probabilidad_exito)
distribucion.mean()

5.0

# Distribución Poisson

La distribución de Poisson modela el número de eventos raros que ocurren en un intervalo de tiempo o espacio específico, dado un valor promedio de ocurrencia, $\lambda$. Esta distribución es útil cuando estamos interesados en eventos que ocurren de manera independiente y a una tasa constante en un intervalo continuo o discreto.

**Notación:**
- $X \sim \text{Poisson}(\lambda)$

**Donde:**
- $\lambda$: Tasa de ocurrencia promedio en un intervalo específico de tiempo o espacio.

**Ejemplo:**

Imaginamos que estamos monitoreando el número de llamadas de emergencia que recibe un centro de atención médica en una ciudad durante una hora. Supongamos que sabemos que la tasa promedio de llamadas de emergencia por hora es de 5. Podemos modelar este escenario utilizando la distribución de Poisson, donde $\lambda = 5$. Luego, podemos usar esta distribución para calcular la probabilidad de recibir un número específico de llamadas de emergencia en una hora determinada.

In [ ]:
# @title Variable aleatoria
from scipy.stats import poisson

# ejemplo: X ~ Poisson(3)
tasa_ocurrencia = 3

# crear VA
va = poisson.rvs(mu=tasa_ocurrencia)
print(va)

4


In [ ]:
# @title Variable aleatoria: múltiples muestras
from scipy.stats import poisson

# ejemplo: X ~ Poisson(3)
tasa_ocurrencia = 3
muestras_aleatorias = 5

# crear VA
va = poisson.rvs(mu=tasa_ocurrencia, size=5)
print(va)

[3 5 1 4 3]


## Función de Masa de Probabilidad (PMF) para Poisson

$ P(X = k) = \frac{{e^{-\lambda} \cdot \lambda^k}}{{k!}}$

Donde:
- $ P(X = k) $ es la probabilidad de que la variable aleatoria $ X $ tome el valor $ k $.
- $ \lambda $ es la tasa de ocurrencia promedio en un intervalo específico de tiempo o espacio.
- $ e $ es la base del logaritmo natural (aproximadamente 2.71828).
- $ k! $ es el factorial de $ k $, es decir, el producto de todos los enteros positivos desde 1 hasta $ k $.


In [ ]:
from scipy.stats import poisson

# ejemplo: X ~ Poisson(3)
tasa_ocurrencia = 3

# número de eventos para calcular la probabilidad
eventos = 2

# probabilidad de obtener exactamente 2 eventos
poisson.pmf(k=eventos, mu=tasa_ocurrencia)

0.22404180765538775

## Función de Distribución Acumulativa (CDF) para Poisson

$ F(k;\lambda) = \sum_{i=0}^{k} \frac{{e^{-\lambda} \cdot \lambda^i}}{{i!}} $

Donde:
- $ F(k;\lambda) $ es la función de distribución acumulativa (CDF) para obtener $ k $ o menos éxitos en $ n $ ensayos, con una tasa de ocurrencia promedio $ \lambda $.
- $ e $ es la base del logaritmo natural (aproximadamente 2.71828).
- $ \lambda $ es la tasa de ocurrencia promedio en un intervalo específico de tiempo o espacio.
- $ i! $ es el factorial de $ i $, es decir, el producto de todos los enteros positivos desde 1 hasta $ i $.


In [ ]:
from scipy.stats import poisson

# ejemplo: X ~ Poisson(10)
tasa_ocurrencia = 10

# número de eventos para calcular la probabilidad
eventos = 8

# probabilidad de obtener 8 o menos eventos
poisson.cdf(k=eventos, mu=tasa_ocurrencia)

0.3328196787507191

## Función de Supervivencia para Poisson (SF)

La función de supervivencia para una distribución de Poisson está dada por la fórmula:

$ P(X > k) = \sum_{i=k+1}^{n} \frac{{e^{-\lambda} \cdot \lambda^i}}{{i!}} $

Donde:
- $ P(X > k) $ es la probabilidad de que la variable aleatoria $ X $ sea mayor que $ k $.
- $ \lambda $ es la tasa de ocurrencia promedio en un intervalo específico de tiempo o espacio.
- $ e $ es la base del logaritmo natural (aproximadamente 2.71828).
- $ i! $ es el factorial de $ i $, es decir, el producto de todos los enteros positivos desde 1 hasta $ i $.
- La suma se realiza desde $ i = k+1 $ hasta $ i = n $.

In [ ]:
from scipy.stats import poisson

# ejemplo: X ~ Poisson(10)
tasa_ocurrencia = 10

# número de eventos para calcular la probabilidad
eventos = 10

# probabilidad de obtener más de 10 eventos
poisson.sf(k=eventos, mu=tasa_ocurrencia)

0.41696024980701485

## Esperanza ($E$)

La esperanza de una distribución de Poisson representa el número promedio de eventos raros que ocurren en un intervalo de tiempo o espacio específico, dados una tasa promedio de ocurrencia $\lambda $.

$$ E(X) = \lambda $$

Donde:
- $E(X)$ es la esperanza de la distribución de Poisson.
- $\lambda $ es la tasa de ocurrencia promedio en el intervalo de tiempo o espacio.


In [ ]:
from scipy.stats import poisson

# ejemplo: X ~ Poisson(10)
tasa_ocurrencia = 10

# crear distribución
distribucion = poisson(mu=tasa_ocurrencia)
distribucion.mean()

10.0